name: CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/aws.key
          chmod 600 ~/.ssh/aws.key
          cat >>~/.ssh/config <<END
          Host aws
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/aws.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.AWS_SSH_USER }}
          SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
          SSH_HOST: ${{ secrets.AWS_SSH_HOST }}

      - name: Update local repository
        run: ssh aws 'cd /opt/cooklens/site && sudo git pull origin master'
        
      - name: Build
        run: ssh aws 'cd /opt/cooklens/site && sudo npm install && sudo npm run build'
